In [1]:
import numpy

def arrays(arr):
    # complete this function
    # use numpy.array
    num= numpy.array(arr,float)
    return numpy.sort(num)

arr = input().strip().split(' ')

-10 -8 1 2 3


In [2]:
arrays(arr)

array([-10.,  -8.,   1.,   2.,   3.])

In [9]:
import numpy
n, m ,p = map(int, input().split())
array_1 = numpy.array([input().strip().split() for _ in range(n)], int)
array_2 = numpy.array([input().strip().split() for _ in range(m)], int)

print(numpy.concatenate((array_1, array_2), axis = 0) )  



2 4 2
1 3 
4 5
2 6
7 2
8 2
5 6
[[1 3]
 [4 5]
 [2 6]
 [7 2]
 [8 2]
 [5 6]]


In [14]:
n, m ,p = map(int, input().split())
print(numpy.zeros((n,m,p),dtype=numpy.int))
print(numpy.ones((n,m,p),dtype=numpy.int))

3 3 3
[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


In [15]:
import numpy

print(str(numpy.eye(*map(int,input().split()))).replace('1',' 1').replace('0',' 0'))




3 3
[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [17]:
import numpy
import numpy

numpy.set_printoptions(sign=' ')

arr = numpy.array(input().split(),float)

print(numpy.floor(arr))
print(numpy.ceil(arr))
print(numpy.rint(arr))


1.1 2.2 3.3 4.4 5.5 6.6 7.7 8.8 9.9
[ 1.  2.  3.  4.  5.  6.  7.  8.  9.]
[  2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  1.   2.   3.   4.   6.   7.   8.   9.  10.]


In [18]:
import numpy
import numpy
n, m  = map(int, input().split())
array_1 = numpy.array([input().strip().split() for _ in range(n)], int)
arr_2=numpy.sum(array_1, axis = 0)
print(numpy.prod(arr_2))   


2 2
1 2
3 4
24


In [19]:
import numpy

n, m  = map(int, input().split())
array_1 = numpy.array([input().strip().split() for _ in range(n)], int)
arr_2=numpy.min(array_1, axis = 1)
print(numpy.max(arr_2))   


4 2 
3 5
1 3
7 0
5 5
5


In [20]:
import numpy
n, m  = map(int, input().split())
array_1 = numpy.array([input().strip().split() for _ in range(n)], int)
print(numpy.mean(array_1,axis=1))
print(numpy.var(array_1,axis=0))
print(numpy.std(array_1,axis=None))




2 2
1 2
3 4
[ 1.5  3.5]
[ 1.  1.]
1.11803398875


In [1]:
import numpy


n=int(input())

arr1=numpy.array([list(map(int,input().split())) for _ in range(n)])

arr2=numpy.array([list(map(int,input().split())) for _ in range(n)])

print(numpy.dot(arr1,arr2))




2
1 4
2 4
1 1
1 3
[[ 5 13]
 [ 6 14]]


In [3]:
import numpy
import numpy 

p = numpy.array(input().split(), float)
x = float(input())
print (numpy.polyval(p, x))

-6 5 4 3 2
2
-32.0


In [5]:
import numpy as np
n=int(input())
array_1 = np.array([input().strip().split() for _ in range(n)], int)
print(np.linalg.det(array_1)) 




2
1 2
3 4
-2.0000000000000004


In [6]:
import numpy as np
n=int(input())
array_1 = np.array([input().strip().split() for _ in range(n)], int)
res=np.linalg.det(array_1)
res_2=round(res,2) 
print(res_2)

2
1 2
2 4
0.0
